DATASET:
  DATA_ROOT: /home/hkzhang/Documents/sdb_a/nas_data
  TRAIN_DATASETS: [CBD_syn, CBD_real]
  TRAIN_DATASETS_WEIGHT: [30, 2]
  CROP_SIZE: 64
  TASK: "denoise"
  LOAD_ALL: False
  TO_GRAY: False
SEARCH:
  TIE_CELL: True
INPUT:
  CROP_SIZE_TRAIN: 64  
SOLVER:
  TRAIN:
    MAX_ITER: 400000
    INIT_LR: 0.025
  CHECKPOINT_PERIOD: 1000
  VALIDATE_PERIOD: 1000
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.5]
DATALOADER:
  BATCH_SIZE_TRAIN: 16
  BATCH_SIZE_TEST: 16
MODEL:
  FILTER_MULTIPLIER: 20
  META_ARCHITECTURE: AMTDiscrete
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 5
  IN_CHANNEL: 3
  PRIMITIVES: "CSDD"

OUTPUT_DIR: output
RESULT_DIR: 4c5n_c
