DATASET:
  DATA_ROOT: /home/a1224062/g_acvt/Architecture_search/nas_data
  DATA_NAME: BSD500_300
  CROP_SIZE: 64
  TASK: "denoise"
  LOAD_ALL: True
  TO_GRAY: True
SEARCH:
  TIE_CELL: True
INPUT:
  CROP_SIZE_TRAIN: 64  
SOLVER:
  TRAIN:
    MAX_ITER: 600000
  CHECKPOINT_PERIOD: 1000
  VALIDATE_PERIOD: 1000
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.6]
DATALOADER:
  BATCH_SIZE_TRAIN: 12
  BATCH_SIZE_TEST: 12
  SIGMA: [70]
  DATA_AUG: 5
MODEL:
  FILTER_MULTIPLIER: 20
  META_ARCHITECTURE: AMTDiscrete
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 5
  IN_CHANNEL: 1
  PRIMITIVES: "CSDD"

OUTPUT_DIR: output
RESULT_DIR: 4c5n_g
