DATASET:
  DATA_ROOT: /home/lidi/Documents/BSR/BSD500/data
  DATA_NAME: BSD500_300
  CROP_SIZE: 64
  TASK: "denoise"
  LOAD_ALL: True
  TO_GRAY: False
SEARCH:
  TIE_CELL: True
INPUT:
  CROP_SIZE_TRAIN: 64  
SOLVER:
  TRAIN:
    MAX_ITER: 800000
  CHECKPOINT_PERIOD: 1000
  VALIDATE_PERIOD: 1000
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.5]
DATALOADER:
  BATCH_SIZE_TRAIN: 4
  BATCH_SIZE_TEST: 4
  SIGMA: [30]
  DATA_AUG: 5
MODEL:
  FILTER_MULTIPLIER: 15
  META_ARCHITECTURE: AMTDiscrete
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 5
  IN_CHANNEL: 3
  PRIMITIVES: "CSDD"

OUTPUT_DIR: output
RESULT_DIR: amt_w_1
