DATASET:
  DATA_ROOT: /home/hkzhang/Documents/sdb_a/nas_data
  DATA_NAME: BSD500_300
  TEST_DATASETS: [BSD500_200]
  CROP_SIZE: 64
  TASK: "denoise"
  TO_GRAY: True
SEARCH:
  TIE_CELL: True
DATALOADER:
  BATCH_SIZE_TEST: 24
  SIGMA: [30]
MODEL:
  FILTER_MULTIPLIER: 20
  META_ARCHITECTURE: AMTDiscrete
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 5
  IN_CHANNEL: 1
  PRIMITIVES: "CSDD"
OUTPUT_DIR: output
RESULT_DIR: 4c5n_g_r1
