DATASET:
  DATA_ROOT: /home/hkzhang/Documents/sdb_a/nas_data
  DATA_NAME: rain800
  CROP_SIZE: 64
  TASK: "derain"
  LOAD_ALL: True
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 20
MODEL:
  META_ARCHITECTURE: AutoMultiTask
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 3
  NUM_BLOCKS: 4
  FILTER_MULTIPLIER: 10
  PRIMITIVES: "CSDD"
  AFFINE: False
DATALOADER:
  BATCH_SIZE_TRAIN: 12
  BATCH_SIZE_TEST: 12
  NUM_WORKERS: 2
  DATA_LIST_DIR: ../preprocess/dataset_json

SOLVER:
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.6]
  MAX_EPOCH: 100

OUTPUT_DIR: output
RESULT_DIR: 3c4n
