DATASET:
  DATA_ROOT: /home/hkzhang/Documents/sdb_a/nas_data
  DATA_NAME: rain800
  CROP_SIZE: 64
  TASK: "derain"
  LOAD_ALL: True
SEARCH:
  TIE_CELL: True
INPUT:
  CROP_SIZE_TRAIN: 64  
SOLVER:
  CHECKPOINT_PERIOD: 1000
  VALIDATE_PERIOD: 1000
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.0]
DATALOADER:
  BATCH_SIZE_TRAIN: 12
  BATCH_SIZE_TEST: 12
MODEL:
  FILTER_MULTIPLIER: 15
  META_ARCHITECTURE: AMTDiscrete
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 3
  NUM_BLOCKS: 4
  PRIMITIVES: "CSDD"

OUTPUT_DIR: output
RESULT_DIR: 3c4n
