DATASET:
  DATA_ROOT: /home/hkzhang/Documents/sdb_a/nas_data
  DATA_NAME: rain100_h
  CROP_SIZE: 64
  TASK: "derain"
  LOAD_ALL: True
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 5
MODEL:
  META_ARCHITECTURE: AutoMultiTask
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 3
  FILTER_MULTIPLIER: 10
  PRIMITIVES: "CSDD"
  AFFINE: False
DATALOADER:
  BATCH_SIZE_TRAIN: 2
  BATCH_SIZE_TEST: 2
  NUM_WORKERS: 2
  DATA_LIST_DIR: ../preprocess/dataset_json

SOLVER:
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.5]
  MAX_EPOCH: 100

OUTPUT_DIR: output
RESULT_DIR: amt_w_1
